services:
  melody:
    build: .
    container_name: melody-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - nodelink
    volumes:
      - ./data:/app/data
    networks:
      - melody-net

  nodelink:
    image: performanc/nodelink:latest
    container_name: melody-nodelink
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "2333"
    environment:
      NODELINK_SERVER_HOST: "0.0.0.0"
      NODELINK_SERVER_PORT: "2333"
      NODELINK_SERVER_PASSWORD: "${NODELINK_PASSWORD}"

      NODELINK_CLUSTER_ENABLED: "true"
      NODELINK_CLUSTER_WORKERS: "0"

      NODELINK_SOURCES_YOUTUBE_ENABLED: "true"
      NODELINK_SOURCES_SOUNDCLOUD_ENABLED: "true"

      NODELINK_SOURCES_SPOTIFY_ENABLED: "${SPOTIFY_ENABLED:-false}"
      NODELINK_SOURCES_SPOTIFY_CLIENTID: "${SPOTIFY_CLIENT_ID:-}"
      NODELINK_SOURCES_SPOTIFY_CLIENTSECRET: "${SPOTIFY_CLIENT_SECRET:-}"

      NODELINK_DEFAULTSEARCHSOURCE: '["youtube", "soundcloud"]'
      NODELINK_UNIFIEDSEARCHSOURCES: '["youtube", "soundcloud"]'
      NODELINK_LOGGING_LEVEL: "info"
    volumes:
      - ./nodelink/logs:/app/logs
      - ./nodelink/.cache:/app/.cache
    networks:
      - melody-net

networks:
  melody-net:
    driver: bridge